image: node:lts

cache:
  paths:
    - node_modules/

before_script:
  - npm install hexo-cli -g
  # --force is temporary due to:
  # https://github.com/sergeyzwezdin/hexo-related-posts/issues/8
  - test -e package.json && npm install --force
  - hexo generate

pages:
  script:
    - hexo generate
  artifacts:
    paths:
      - public
  only:
    - master
